src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompteRepository::class)]
class Compte
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $num_compte = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?float $solde = null;

    #[ORM\ManyToOne(inversedBy: 'comptes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(nullable: true)]
    private ?int $id_agent = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCompte(): ?string
    {
        return $this->num_compte;
    }

    public function setNumCompte(string $num_compte): self
    {
        $this->num_compte = $num_compte;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getSolde(): ?float
    {
        return $this->solde;
    }

    public function setSolde(float $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getIdAgent(): ?int
    {
        return $this->id_agent;
    }

    public function setIdAgent(?int $id_agent): self
    {
        $this->id_agent = $id_agent;

        return $this;
    }

}

src/Form/CompteType.php
<?php

namespace App\Form;

use App\Entity\Compte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CompteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_compte')
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Epargne' => 'Epargne',
                    'Courant sans découvert' => 'Compte courant sans découvert',
                    'Courant avec découvert' => 'Compte courant avec découvert',
                ],
            ]
        )
            ->add('solde')
            // ->add('date_creation')
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Compte::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Demande;
use App\Entity\Compte;
use App\Entity\User;
use App\Form\CompteType;
use App\Repository\CompteRepository;
use App\Repository\DemandeRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/agent/compte')]
class CompteController extends AbstractController
{
    #[Route('/', name: 'app_compte_index', methods: ['GET'])]
    public function index(CompteRepository $compteRepository): Response
    {
        return $this->render('compte/index.html.twig', [
            'comptes' => $compteRepository->findBy(array("id_agent" => $this->getUser()->getId())),
        ]);
    }

    #[Route('/new', name: 'app_compte_new', methods: ['GET', 'POST'])]

    public function new(Request $request, CompteRepository $compteRepository, UserRepository $userRepository): Response
    {
        $compte = new Compte();
        if ($request->getMethod() == 'POST') {
                $idAgent = $request->get('idAgent');
                $typeCompte= $request->get('typeCompte');
                $client= $userRepository->find($request->get('idClient'));
                $compte->setType($typeCompte);
                $compte->setSolde(0.0);
                $compte->setDateCreation(new \DateTimeImmutable());
                $compte->setIdAgent($idAgent);
                $compte->setUser($client);
                $compte->setNumCompte('4586658'. random_int(9999, 999999));
                $compteRepository->save($compte, true);
        }
            return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/{id}', name: 'app_compte_show', methods: ['GET'])]
    public function show(Compte $compte): Response
    {
        return $this->render('compte/show.html.twig', [
            'compte' => $compte,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_compte_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Compte $compte, CompteRepository $compteRepository): Response
    {
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $compteRepository->save($compte, true);
            $this->addFlash(type: 'success', message: "Compte édité avec succès");
            return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('compte/edit.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_compte_delete', methods: ['POST'])]
    public function delete(Request $request, Compte $compte, CompteRepository $compteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$compte->getId(), $request->request->get('_token'))) {
            $compteRepository->remove($compte, true);
        }

        return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/compte/_delete_form.html.twig
<form method="post" action="{{ path('app_compte_delete', {'id': compte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ compte.id) }}">
    <button class="btn btn-danger my-2">Supprimer</button>
</form>

templates/compte/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/compte/edit.html.twig
{% extends 'dashboard/index_agent.html.twig' %}

{% block title %}Edit Compte{% endblock %}

{% block body %}
    <h1>Modifier Compte</h1>

    <div class="container">{{ include('compte/_form.html.twig', {'button_label': 'Modifier'}) }}
        <a class="text-decoration-none btn-warning  py-1 px-4 border-2" href="{{ path('app_compte_index') }}">Revenir</a>

        {{ include('compte/_delete_form.html.twig') }}
    </div>


{% endblock %}

templates/compte/index.html.twig
{% extends 'dashboard/index_agent.html.twig' %}

{% block title %}Compte index{% endblock %}

{% block body %}
    <h1>Compte index</h1>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num_compte</th>
                <th>Type</th>
                <th>Solde</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for compte in comptes %}
            <tr>
                <td>{{ compte.id }}</td>
                <td>{{ compte.numCompte }}</td>
                <td>{{ compte.type }}</td>
                <td>{{ compte.solde }}</td>
                <td>{{ compte.dateCreation ? compte.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <button class="btn-primary rounded-3 px-4"><a class="text-white text-decoration-none " href="{{ path('app_compte_show', {'id': compte.id}) }}">Voir</a></button>
                    <button class="btn-warning rounded-3"><a class="text-white text-decoration-none " href="{{ path('app_compte_edit', {'id': compte.id}) }}">Modifier</a></button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/compte/new.html.twig
{% extends 'dashboard/index_agent.html.twig' %}

{% block title %}New Compte{% endblock %}

{% block body %}
    <h1>Create new Compte</h1>

    {{ include('compte/_form.html.twig') }}

    <a href="{{ path('app_compte_index') }}">back to list</a>
{% endblock %}

templates/compte/show.html.twig
{% extends 'dashboard/index_agent.html.twig' %}

{% block title %}Compte{% endblock %}

{% block body %}
    <h1>Compte</h1>

    <table class="table d-flex">
        <tbody>
            <tr>
                <th>Id :</th>
                <td>{{ compte.id }}</td>
            </tr>
            <tr>
                <th>Client :</th>
                <td>{{ compte.User.email }}</td>
            </tr>
            <tr>
                <th>Num_compte :</th>
                <td>{{ compte.numCompte }}</td>
            </tr>
            <tr>
                <th>Type :</th>
                <td>{{ compte.type }}</td>
            </tr>
            <tr>
                <th>Solde :</th>
                <td>{{ compte.solde }}</td>
            </tr>
            <tr>
                <th>Date_creation :</th>
                <td>{{ compte.dateCreation ? compte.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="text-decoration-none d-block mb-2" href="{{ path('app_compte_index') }}">Revenir à la liste</a>

    <a class="text-decoration-none btn-warning  py-1 px-4 border-2 " href="{{ path('app_compte_edit', {'id': compte.id}) }}">Modifier</a>

    {{ include('compte/_delete_form.html.twig') }}
{% endblock %}